echo " "
echo " "
echo "  PPPPPPPPPPPPPPPPP    TTTTTTTTTTTTTTTTTTTTTTT        CCCCCCCCCCCCC"
echo "  P::::::::::::::::P   T:::::::::::::::::::::T     CCC::::::::::::C"
echo "  P::::::PPPPPP:::::P  T:::::::::::::::::::::T   CC:::::::::::::::C"
echo "  PP:::::P     P:::::P T:::::TT:::::::TT:::::T  C:::::CCCCCCCC::::C"
echo "    P::::P     P:::::P TTTTTT  T:::::T  TTTTTT C:::::C       CCCCCC"
echo "    P::::P     P:::::P         T:::::T        C:::::C              "
echo "    P::::PPPPPP:::::P          T:::::T        C:::::C              "
echo "    P:::::::::::::PP           T:::::T        C:::::C              "
echo "    P::::PPPPPPPPP             T:::::T        C:::::C              "
echo "    P::::P                     T:::::T        C:::::C              "
echo "    P::::P                     T:::::T        C:::::C              "
echo "    P::::P                     T:::::T         C:::::C       CCCCCC"
echo "  PP::::::PP                 TT:::::::TT        C:::::CCCCCCCC::::C"
echo "  P::::::::P                 T:::::::::T         CC:::::::::::::::C"
echo "  P::::::::P                 T:::::::::T           CCC::::::::::::C"
echo "  PPPPPPPPPP                 TTTTTTTTTTT              CCCCCCCCCCCCC  Co."
echo " "
echo " "
